---
apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-alpine
  namespace: default
spec:
  containers:
  - name: csi-s3-test-nginx
    image: alpine:3.21.2
    command: ["sleep", "300"]
    volumeMounts:
      - mountPath: /mnt/s3
        name: s3
  volumes:
  - name: s3
    persistentVolumeClaim:
      claimName: csi-s3-pvc-dynamic
      readOnly: false