# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: mysql-operator-api-full-access
#   namespace: mysql-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-api-access
  namespace: mysql-operator