apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  # shareProcessNamespace: true
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 80
