apiVersion: v2
name: homework
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: ~16.2
    repository: "oci://registry-1.docker.io/bitnamicharts"
