apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "otus"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"
          secretRef:
            name: "vault-auth-secret"
            key: "vault"