---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault
automountServiceAccountToken: true

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
