apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homework.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       {{ .Values.nginx.port }};
        server_name  {{ .Values.nginx.serverName }};

        location / {
            root   {{ .Values.nginx.rootDir }};
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
