repositories:
  - name: bitnamicharts
    url: registry-1.docker.io/bitnamicharts
    oci: true

releases:
- name: kafka
  namespace: dev
  createNamespace: true
  chart: bitnamicharts/kafka
  version: 31.0.0
  values:
    - values-dev.yaml

- name: kafka
  namespace: prod
  createNamespace: true
  chart: bitnamicharts/kafka
  version: 31.0.0
  values:
    - values-prod.yaml